import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as kms from 'aws-cdk-lib/aws-kms';

export class InfraStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // --- DynamoDB Table ---
    // Table name is auto-generated by CDK. This avoids name conflicts
    // when deploying multiple stacks in the same account.

    const table = new dynamodb.Table(this, 'VirtualWaitingRoom', {
      partitionKey: { name: 'PK', type: dynamodb.AttributeType.STRING },
      sortKey: { name: 'SK', type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      stream: dynamodb.StreamViewType.NEW_AND_OLD_IMAGES,
      timeToLiveAttribute: 'ExpiresAt',
    });

    table.addGlobalSecondaryIndex({
      indexName: 'SessionMetadataIndex',
      partitionKey: { name: 'GSIPK', type: dynamodb.AttributeType.STRING },
      projectionType: dynamodb.ProjectionType.KEYS_ONLY,
    });

    // --- KMS Asymmetric Key for JWT Signing ---

    const signingKey = new kms.Key(this, 'JwtSigningKey', {
      keySpec: kms.KeySpec.ECC_NIST_P256,
      keyUsage: kms.KeyUsage.SIGN_VERIFY,
      description: 'Asymmetric key for signing JWT tokens in the Virtual Waiting Room',
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      pendingWindow: cdk.Duration.days(7),
    });
    signingKey.addAlias(`alias/virtual-waiting-room-jwt-signing-${this.stackName}`);

    // --- IAM Roles ---
    // No manual IAM roles defined here. Lambda functions in later phases
    // will create their own execution roles via CDK's lambda.Function,
    // with inline grants like table.grantWriteData(fn) and signingKey.grantSign(fn).
    // This avoids boilerplate and follows CDK best practices.

    // --- Outputs ---

    new cdk.CfnOutput(this, 'TableName', {
      value: table.tableName,
      description: 'DynamoDB table name',
    });

    new cdk.CfnOutput(this, 'TableArn', {
      value: table.tableArn,
      description: 'DynamoDB table ARN',
    });

    new cdk.CfnOutput(this, 'SigningKeyId', {
      value: signingKey.keyId,
      description: 'KMS signing key ID',
    });

    new cdk.CfnOutput(this, 'SigningKeyArn', {
      value: signingKey.keyArn,
      description: 'KMS signing key ARN',
    });
  }
}
